"""Install, compose, and register the Ted's Dashboard.

Responsibilities (all coexistence-/override-safe):

* Copy the bundled managed content into ``<config>/dashboards/ted-dashboard/``
  (overwritten wholesale on every install — the integration owns it).
* Scaffold ``<config>/dashboards/ted-dashboard-user/`` overlay dirs + a README,
  once, and never touch them again (the user owns them).
* Generate ``<config>/dashboards/ted-dashboard.yaml`` — an ``!include`` list
  composed with override precedence: a user ``overrides/<view>.yaml`` wins over
  the managed view, then user ``views/*`` are appended.
* Register a yaml-mode Lovelace dashboard at runtime (no configuration.yaml
  edit) via ``LovelaceYAML`` + ``frontend.async_register_built_in_panel``.
"""

from __future__ import annotations

import json
import logging
import os
import shutil
import tempfile
from pathlib import Path
from typing import Any

from homeassistant.core import HomeAssistant, callback

from .const import (
    DASHBOARD_BUNDLE_DIR,
    DASHBOARD_ICON,
    DASHBOARD_MAIN_FILE,
    DASHBOARD_MANAGED_DIR,
    DASHBOARD_SLUG,
    DASHBOARD_TITLE,
    DASHBOARD_USER_DIR,
    DASHBOARDS_DIR,
    VERSIONS_FILE,
)
from .updater import async_load_installer_state

_LOGGER = logging.getLogger(__name__)

_USER_SUBDIRS = ("views", "overrides", "shared")
_GENERATED_HEADER = (
    "# GENERATED by Ted's Dashboard System — do NOT edit this file.\n"
    "# It is regenerated on every install/update. To customize:\n"
    "#   * add your own views in ted-dashboard-user/views/\n"
    "#   * fork a shipped view by copying it into ted-dashboard-user/overrides/\n"
    "#   * reorder / hide views from Settings -> Dashboard.\n"
)
_USER_README = (
    "# Ted's Dashboard — your overrides\n\n"
    "Anything in this folder is **yours** and is never modified by updates.\n\n"
    "- `views/` — drop in your own view YAML files; they're appended to the dashboard.\n"
    "- `overrides/` — copy a shipped view here (same filename) to fork it; your copy\n"
    "  is used instead, but it then stops receiving upstream updates for that view.\n"
    "- `shared/` — custom shared includes referenced by your views.\n\n"
    "The managed content lives in `../ted-dashboard/` and is overwritten on update —\n"
    "don't edit it there.\n"
)


def _bundle_dir() -> str:
    return os.path.join(os.path.dirname(__file__), DASHBOARD_BUNDLE_DIR)


def _read_json(path: str) -> dict[str, Any]:
    try:
        with open(path, encoding="utf-8") as fh:
            data = json.load(fh)
            return data if isinstance(data, dict) else {}
    except (OSError, ValueError):
        return {}


def _version_tuple(value: Any) -> tuple[int, ...]:
    parts: list[int] = []
    for part in str(value).split("."):
        try:
            parts.append(int(part))
        except ValueError:
            parts.append(0)
    return tuple(parts)


def _version_gt(a: Any, b: Any) -> bool:
    """True when version ``a`` is strictly newer than ``b``."""
    return _version_tuple(a) > _version_tuple(b)


def _mirror_dir(src: str, dest: str) -> None:
    """Replace ``dest`` with a fresh copy of ``src`` (managed content only)."""
    if os.path.isdir(dest):
        shutil.rmtree(dest)
    shutil.copytree(src, dest)


def _scaffold_user_dir(dashboards_dir: str) -> None:
    """Create the user overlay dirs + README once; never overwrite them."""
    base = os.path.join(dashboards_dir, DASHBOARD_USER_DIR)
    for sub in _USER_SUBDIRS:
        os.makedirs(os.path.join(base, sub), exist_ok=True)
    readme = os.path.join(base, "README.md")
    if not os.path.isfile(readme):
        with open(readme, "w", encoding="utf-8") as fh:
            fh.write(_USER_README)


def effective_view_order(
    canonical_order: list, layout_ovr: dict | None
) -> tuple[list[str], set[str]]:
    """Apply the user's reorder + hide overrides to the shipped view order.

    ``canonical_order`` is ``versions["layout"]["order"]`` (relative paths). The
    override ``layout_ovr`` holds ``order`` and ``hidden`` as lists of view *basenames*.
    Returns ``(ordered_rel_paths, hidden_basenames)`` — the ordered list includes hidden
    views (callers decide whether to skip them).
    """
    by_base = {os.path.basename(rel): rel for rel in canonical_order}
    user_order = (layout_ovr or {}).get("order") or []
    hidden = set((layout_ovr or {}).get("hidden") or [])
    ordered: list[str] = []
    seen: set[str] = set()
    for base in user_order:
        rel = by_base.get(base)
        if rel and base not in seen:
            ordered.append(rel)
            seen.add(base)
    for rel in canonical_order:
        base = os.path.basename(rel)
        if base not in seen:
            ordered.append(rel)
            seen.add(base)
    return ordered, hidden


def _compose_main(
    dashboards_dir: str, versions: dict[str, Any], layout_ovr: dict | None = None
) -> str:
    """Build the generated main dashboard yaml (an include list) as text."""
    canonical = versions.get("layout", {}).get("order", [])
    ordered, hidden = effective_view_order(canonical, layout_ovr)
    user_overrides = os.path.join(dashboards_dir, DASHBOARD_USER_DIR, "overrides")
    user_views = os.path.join(dashboards_dir, DASHBOARD_USER_DIR, "views")

    lines = [_GENERATED_HEADER]
    lines.append("views:")
    for rel in ordered:
        name = os.path.basename(rel)
        if name in hidden:
            continue
        if os.path.isfile(os.path.join(user_overrides, name)):
            lines.append(f"  - !include {DASHBOARD_USER_DIR}/overrides/{name}")
        else:
            lines.append(f"  - !include {DASHBOARD_MANAGED_DIR}/{rel}")
    if os.path.isdir(user_views):
        for name in sorted(os.listdir(user_views)):
            if name.endswith((".yaml", ".yml")):
                lines.append(f"  - !include {DASHBOARD_USER_DIR}/views/{name}")
    return "\n".join(lines) + "\n"


def _write_text(path: str, text: str) -> None:
    os.makedirs(os.path.dirname(path), exist_ok=True)
    with open(path, "w", encoding="utf-8") as fh:
        fh.write(text)
    # Bump mtime so HA's yaml-dashboard cache re-reads it (hot reload).
    os.utime(path, None)


def _install_sync(
    bundle_managed: str, versions: dict, config_dir: str, mirror: bool,
    layout_ovr: dict | None = None,
) -> None:
    """Blocking filesystem work: (optionally) mirror managed, scaffold, compose."""
    dashboards_dir = os.path.join(config_dir, DASHBOARDS_DIR)
    if mirror:
        _mirror_dir(bundle_managed, os.path.join(dashboards_dir, DASHBOARD_MANAGED_DIR))
    _scaffold_user_dir(dashboards_dir)
    _write_text(
        os.path.join(dashboards_dir, DASHBOARD_MAIN_FILE),
        _compose_main(dashboards_dir, versions, layout_ovr),
    )


@callback
def _register_dashboard(hass: HomeAssistant) -> None:
    """Register the yaml-mode dashboard panel (runtime, no configuration.yaml)."""
    try:
        from homeassistant.components import frontend
        from homeassistant.components.lovelace.const import (
            CONF_ICON,
            CONF_REQUIRE_ADMIN,
            CONF_SHOW_IN_SIDEBAR,
            CONF_TITLE,
            CONF_URL_PATH,
            LOVELACE_DATA,
            MODE_YAML,
        )
        from homeassistant.components.lovelace.dashboard import LovelaceYAML
        from homeassistant.const import CONF_FILENAME, CONF_MODE
    except ImportError:  # pragma: no cover - lovelace internals moved
        _LOGGER.warning(
            "Lovelace internals unavailable; the Ted's Dashboard files were "
            "installed but the panel was not auto-registered."
        )
        return

    data = hass.data.get(LOVELACE_DATA)
    if data is None:
        _LOGGER.warning("Lovelace not set up; cannot register the Ted's Dashboard panel")
        return

    filename = f"{DASHBOARDS_DIR}/{DASHBOARD_MAIN_FILE}"
    conf = {
        CONF_MODE: MODE_YAML,
        CONF_FILENAME: filename,
        CONF_TITLE: DASHBOARD_TITLE,
        CONF_ICON: DASHBOARD_ICON,
        CONF_SHOW_IN_SIDEBAR: True,
        CONF_REQUIRE_ADMIN: False,
        CONF_URL_PATH: DASHBOARD_SLUG,
    }
    data.dashboards[DASHBOARD_SLUG] = LovelaceYAML(hass, DASHBOARD_SLUG, conf)
    if not frontend.async_panel_exists(hass, DASHBOARD_SLUG):
        frontend.async_register_built_in_panel(
            hass,
            "lovelace",
            sidebar_title=DASHBOARD_TITLE,
            sidebar_icon=DASHBOARD_ICON,
            frontend_url_path=DASHBOARD_SLUG,
            config={"mode": MODE_YAML},
            require_admin=False,
            update=False,
        )
    _LOGGER.info("Registered Ted's Dashboard at /%s", DASHBOARD_SLUG)


@callback
def async_unregister_dashboard(hass: HomeAssistant) -> None:
    """Remove the dashboard panel (on unload/uninstall). Files are left in place."""
    try:
        from homeassistant.components import frontend
        from homeassistant.components.lovelace.const import LOVELACE_DATA
    except ImportError:  # pragma: no cover
        return
    frontend.async_remove_panel(hass, DASHBOARD_SLUG, warn_if_unknown=False)
    if (data := hass.data.get(LOVELACE_DATA)) is not None:
        data.dashboards.pop(DASHBOARD_SLUG, None)


def _remove_managed(dashboards_dir: str) -> None:
    """Delete the generated main file + managed content, KEEPING the user overlay."""
    main = os.path.join(dashboards_dir, DASHBOARD_MAIN_FILE)
    if os.path.isfile(main):
        os.remove(main)
    managed = os.path.join(dashboards_dir, DASHBOARD_MANAGED_DIR)
    if os.path.isdir(managed):
        shutil.rmtree(managed, ignore_errors=True)
    # ted-dashboard-user/ (the user's own views/overrides/shared) is intentionally kept.


async def async_remove_dashboard_files(hass: HomeAssistant) -> None:
    """On uninstall: remove the generated + managed dashboard files, keeping the
    user overlay (``ted-dashboard-user/``) so hand-authored customizations survive."""
    dashboards_dir = os.path.join(hass.config.config_dir, DASHBOARDS_DIR)
    await hass.async_add_executor_job(_remove_managed, dashboards_dir)


async def async_install_dashboard(hass: HomeAssistant) -> None:
    """Install the bundled dashboard, compose the main file, and register it.

    The managed content is only re-mirrored from the bundle when nothing is
    installed yet or the bundled baseline is newer than what's installed (so a
    later downloaded update is never reverted to the baseline). The main file is
    always recomposed (to pick up user overlay changes) and the panel is always
    registered (panels reset on restart).
    """
    bundle_managed = os.path.join(_bundle_dir(), DASHBOARD_MANAGED_DIR)
    if not await hass.async_add_executor_job(os.path.isdir, bundle_managed):
        _LOGGER.debug("No bundled dashboard content; skipping dashboard install")
        return
    versions = await hass.async_add_executor_job(
        _read_json, os.path.join(_bundle_dir(), VERSIONS_FILE)
    )
    store, state = await async_load_installer_state(hass)
    installed = state.get("versions", {}).get("dashboard")
    need_content = installed is None or _version_gt(
        versions.get("dashboard", "0"), installed.get("dashboard", "0")
    )
    await hass.async_add_executor_job(
        _install_sync, bundle_managed, versions, hass.config.config_dir, need_content,
        state.get("layout") or {},
    )
    _register_dashboard(hass)

    if need_content:
        state.setdefault("versions", {})["dashboard"] = versions
        await store.async_save(state)


def _mkdtemp() -> str:
    return tempfile.mkdtemp(prefix="teds_dash_")


def _rmtree_quiet(path: str) -> None:
    shutil.rmtree(path, ignore_errors=True)


def _install_downloaded(
    tmp: str, dashboards_dir: str, versions: dict, layout_ovr: dict | None = None
) -> None:
    _mirror_dir(tmp, os.path.join(dashboards_dir, DASHBOARD_MANAGED_DIR))
    _scaffold_user_dir(dashboards_dir)
    _write_text(
        os.path.join(dashboards_dir, DASHBOARD_MAIN_FILE),
        _compose_main(dashboards_dir, versions, layout_ovr),
    )


def _recompose_sync(
    dashboards_dir: str, versions: dict, layout_ovr: dict | None = None
) -> None:
    _scaffold_user_dir(dashboards_dir)
    _write_text(
        os.path.join(dashboards_dir, DASHBOARD_MAIN_FILE),
        _compose_main(dashboards_dir, versions, layout_ovr),
    )


async def async_recompose(hass: HomeAssistant) -> None:
    """Regenerate the main dashboard file from current managed + user overlays.

    Called after a user override/custom-view change so the include list picks up
    the new files (and HA hot-reloads via the bumped mtime).
    """
    _, state = await async_load_installer_state(hass)
    versions = state.get("versions", {}).get("dashboard", {})
    if not versions:
        versions = await hass.async_add_executor_job(
            _read_json, os.path.join(_bundle_dir(), VERSIONS_FILE)
        )
    dashboards_dir = os.path.join(hass.config.config_dir, DASHBOARDS_DIR)
    await hass.async_add_executor_job(
        _recompose_sync, dashboards_dir, versions, state.get("layout") or {}
    )


async def async_download_and_install(
    hass: HomeAssistant, github: Any, versions_remote: dict[str, Any]
) -> dict[str, Any] | None:
    """Download the managed dashboard content from GitHub and (re)install it.

    Returns the remote versions on success, or ``None`` if nothing was
    downloaded (e.g. the repo path was empty).
    """
    tmp = await hass.async_add_executor_job(_mkdtemp)
    try:
        count = await github.async_download_dir(
            f"{DASHBOARDS_DIR}/{DASHBOARD_MANAGED_DIR}", Path(tmp)
        )
        if not count:
            return None
        dashboards_dir = os.path.join(hass.config.config_dir, DASHBOARDS_DIR)
        _, state = await async_load_installer_state(hass)
        await hass.async_add_executor_job(
            _install_downloaded, tmp, dashboards_dir, versions_remote,
            state.get("layout") or {},
        )
        _register_dashboard(hass)
        return versions_remote
    finally:
        await hass.async_add_executor_job(_rmtree_quiet, tmp)
